//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnoSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREW_PERSON
    {
        public int IdCrewPerson { get; set; }
        public Nullable<int> IdPerson { get; set; }
        public Nullable<int> IdCrew { get; set; }
    
        public virtual CREW CREW { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
