//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnoSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVOICE()
        {
            this.INVOICE_PRODUCT = new HashSet<INVOICE_PRODUCT>();
        }
    
        public int IdInvoice { get; set; }
        public int IdPerson { get; set; }
        public double TotalPrice { get; set; }
        public string Address { get; set; }
        public string Department { get; set; }
        public string City { get; set; }
        public System.DateTime RegisteredAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE_PRODUCT> INVOICE_PRODUCT { get; set; }
    }
}
