//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnoSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public int IdInvoice { get; set; }
        public int IdPerson { get; set; }
        public int IdProduct { get; set; }
        public string NameProduct { get; set; }
        public double Quantity { get; set; }
        public double UnitPrice { get; set; }
        public double TotalPriceProduct { get; set; }
        public string Address { get; set; }
        public string Department { get; set; }
        public string City { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
