//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnoSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public int Id_Person { get; set; }
        public int Id_Role { get; set; }
        public string FirtsName { get; set; }
        public string LastName { get; set; }
        public string DocumentNumber { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Department { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual ROLE ROLE { get; set; }
    }
}
