//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnoSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_PERSON
    {
        public int IdProductPerson { get; set; }
        public Nullable<int> IdPerson { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public string NameProduct { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> TotalPriceProduct { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
