//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnoSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUOTE_SERVICE
    {
        public int IdQuoteService { get; set; }
        public Nullable<int> IdQuote { get; set; }
        public Nullable<int> IdService { get; set; }
        public Nullable<double> ServicePrice { get; set; }
    
        public virtual QUOTE QUOTE { get; set; }
        public virtual SERVICE SERVICE { get; set; }
    }
}
