//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnoSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUOTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUOTE()
        {
            this.QUOTE_PRODUCT = new HashSet<QUOTE_PRODUCT>();
        }
    
        public int IdQuote { get; set; }
        public Nullable<int> IdPerson { get; set; }
        public Nullable<int> IdState { get; set; }
        public int IdCrewPerson { get; set; }
        public string ServiceAddress { get; set; }
        public string ServiceDepartment { get; set; }
        public string ServiceCity { get; set; }
        public System.DateTime StarDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUOTE_PRODUCT> QUOTE_PRODUCT { get; set; }
        public virtual STATE STATE { get; set; }
    }
}
